[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
clap.workspace = true
anyhow.workspace = true
tokio.workspace = true
tokio-utils.workspace = true
connection.workspace = true