[workspace]
members = [
    "client",
    "server",
    "common",
]

[workspace.dependencies]
common = { path = "../common" }
clap = { version = "4.2.1", features = ["derive"] }
anyhow = "1.0.69"
tokio = { version = "1.26.0", features = ["full"] }
tokio-utils = "0.1.2"
connection = "0.2.5"